# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\danie\Documents\Proyecto Taller\CafeNostro\nostro\admin_usuarios\formulario_usuario_ui.ui'
#
# Created: Mon Nov 09 23:03:00 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FormularioUsuario(object):
    def setupUi(self, FormularioUsuario):
        FormularioUsuario.setObjectName("FormularioUsuario")
        FormularioUsuario.setEnabled(True)
        FormularioUsuario.resize(384, 289)
        self.verticalLayout_3 = QtGui.QVBoxLayout(FormularioUsuario)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(FormularioUsuario)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_cambiar_c = QtGui.QLabel(self.groupBox)
        self.label_cambiar_c.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cambiar_c.setObjectName("label_cambiar_c")
        self.verticalLayout.addWidget(self.label_cambiar_c)
        self.label_clave_actual = QtGui.QLabel(self.groupBox)
        self.label_clave_actual.setObjectName("label_clave_actual")
        self.verticalLayout.addWidget(self.label_clave_actual)
        self.label_clave = QtGui.QLabel(self.groupBox)
        self.label_clave.setObjectName("label_clave")
        self.verticalLayout.addWidget(self.label_clave)
        self.label_verif = QtGui.QLabel(self.groupBox)
        self.label_verif.setObjectName("label_verif")
        self.verticalLayout.addWidget(self.label_verif)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_nombre = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.verticalLayout_2.addWidget(self.lineEdit_nombre)
        self.lineEdit_apellido = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_apellido.setObjectName("lineEdit_apellido")
        self.verticalLayout_2.addWidget(self.lineEdit_apellido)
        self.pushButton_cambiar_c = QtGui.QPushButton(self.groupBox)
        self.pushButton_cambiar_c.setObjectName("pushButton_cambiar_c")
        self.verticalLayout_2.addWidget(self.pushButton_cambiar_c)
        self.lineEdit_clave_actual = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_clave_actual.setObjectName("lineEdit_clave_actual")
        self.verticalLayout_2.addWidget(self.lineEdit_clave_actual)
        self.lineEdit_clave = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_clave.setObjectName("lineEdit_clave")
        self.verticalLayout_2.addWidget(self.lineEdit_clave)
        self.lineEdit_verif = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_verif.setObjectName("lineEdit_verif")
        self.verticalLayout_2.addWidget(self.lineEdit_verif)
        self.lineEdit_rut = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_rut.setObjectName("lineEdit_rut")
        self.verticalLayout_2.addWidget(self.lineEdit_rut)
        self.comboBox_tipo = QtGui.QComboBox(self.groupBox)
        self.comboBox_tipo.setObjectName("comboBox_tipo")
        self.verticalLayout_2.addWidget(self.comboBox_tipo)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(FormularioUsuario)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(FormularioUsuario)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), FormularioUsuario.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), FormularioUsuario.reject)
        QtCore.QMetaObject.connectSlotsByName(FormularioUsuario)

    def retranslateUi(self, FormularioUsuario):
        FormularioUsuario.setWindowTitle(QtGui.QApplication.translate("FormularioUsuario", "Formulario Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FormularioUsuario", "Datos de Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormularioUsuario", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FormularioUsuario", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cambiar_c.setText(QtGui.QApplication.translate("FormularioUsuario", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.label_clave_actual.setText(QtGui.QApplication.translate("FormularioUsuario", "Contraseña actual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_clave.setText(QtGui.QApplication.translate("FormularioUsuario", "Contraseña", None, QtGui.QApplication.UnicodeUTF8))
        self.label_verif.setText(QtGui.QApplication.translate("FormularioUsuario", "Repita contraseña", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormularioUsuario", "Rut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormularioUsuario", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cambiar_c.setText(QtGui.QApplication.translate("FormularioUsuario", "Cambiar Contraseña", None, QtGui.QApplication.UnicodeUTF8))

