# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numero_pagos.ui'
#
# Created: Fri Dec 11 20:49:42 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NumeroPagos(object):
    def setupUi(self, NumeroPagos):
        NumeroPagos.setObjectName("NumeroPagos")
        NumeroPagos.resize(477, 461)
        self.verticalLayout_3 = QtGui.QVBoxLayout(NumeroPagos)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(NumeroPagos)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinBox_numero_pagos = QtGui.QSpinBox(NumeroPagos)
        self.spinBox_numero_pagos.setObjectName("spinBox_numero_pagos")
        self.horizontalLayout_4.addWidget(self.spinBox_numero_pagos)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tableWidget_resumen = QtGui.QTableWidget(NumeroPagos)
        self.tableWidget_resumen.setMinimumSize(QtCore.QSize(459, 292))
        self.tableWidget_resumen.setObjectName("tableWidget_resumen")
        self.tableWidget_resumen.setColumnCount(0)
        self.tableWidget_resumen.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_resumen)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(NumeroPagos)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lcdNumber_subtotal = QtGui.QLCDNumber(NumeroPagos)
        self.lcdNumber_subtotal.setMinimumSize(QtCore.QSize(76, 0))
        self.lcdNumber_subtotal.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_subtotal.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdNumber_subtotal.setSmallDecimalPoint(True)
        self.lcdNumber_subtotal.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber_subtotal.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_subtotal.setProperty("value", 0.0)
        self.lcdNumber_subtotal.setObjectName("lcdNumber_subtotal")
        self.horizontalLayout.addWidget(self.lcdNumber_subtotal)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_4 = QtGui.QLabel(NumeroPagos)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lcdNumber_propina = QtGui.QLCDNumber(NumeroPagos)
        self.lcdNumber_propina.setMinimumSize(QtCore.QSize(76, 0))
        self.lcdNumber_propina.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_propina.setSmallDecimalPoint(True)
        self.lcdNumber_propina.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_propina.setObjectName("lcdNumber_propina")
        self.horizontalLayout_2.addWidget(self.lcdNumber_propina)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label = QtGui.QLabel(NumeroPagos)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lcdNumber_total = QtGui.QLCDNumber(NumeroPagos)
        self.lcdNumber_total.setMinimumSize(QtCore.QSize(76, 0))
        self.lcdNumber_total.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber_total.setSmallDecimalPoint(True)
        self.lcdNumber_total.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_total.setObjectName("lcdNumber_total")
        self.horizontalLayout_3.addWidget(self.lcdNumber_total)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.groupBox = QtGui.QGroupBox(NumeroPagos)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_numero_pagos = QtGui.QVBoxLayout()
        self.verticalLayout_numero_pagos.setObjectName("verticalLayout_numero_pagos")
        self.verticalLayout.addLayout(self.verticalLayout_numero_pagos)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.pushButton_pagar = QtGui.QPushButton(NumeroPagos)
        self.pushButton_pagar.setObjectName("pushButton_pagar")
        self.verticalLayout_3.addWidget(self.pushButton_pagar)

        self.retranslateUi(NumeroPagos)
        QtCore.QMetaObject.connectSlotsByName(NumeroPagos)

    def retranslateUi(self, NumeroPagos):
        NumeroPagos.setWindowTitle(QtGui.QApplication.translate("NumeroPagos", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NumeroPagos", "Ingresa número de pagos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NumeroPagos", "Subtotal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NumeroPagos", "Propina (10%):", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NumeroPagos", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pagar.setText(QtGui.QApplication.translate("NumeroPagos", "Pagar", None, QtGui.QApplication.UnicodeUTF8))

