# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario_empresa.ui'
#
# Created: Sun Dec 20 20:37:19 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FormularioEmpresa(object):
    def setupUi(self, FormularioEmpresa):
        FormularioEmpresa.setObjectName("FormularioEmpresa")
        FormularioEmpresa.resize(842, 372)
        self.verticalLayout = QtGui.QVBoxLayout(FormularioEmpresa)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(FormularioEmpresa)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, 20, -1, 20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_fono = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_fono.setObjectName("lineEdit_fono")
        self.gridLayout.addWidget(self.lineEdit_fono, 6, 1, 1, 1)
        self.lineEdit_email = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 7, 1, 1, 1)
        self.label_error_email = QtGui.QLabel(self.groupBox)
        self.label_error_email.setObjectName("label_error_email")
        self.gridLayout.addWidget(self.label_error_email, 7, 2, 1, 1)
        self.label_error_giro = QtGui.QLabel(self.groupBox)
        self.label_error_giro.setObjectName("label_error_giro")
        self.gridLayout.addWidget(self.label_error_giro, 5, 2, 1, 1)
        self.label_error_ciudad = QtGui.QLabel(self.groupBox)
        self.label_error_ciudad.setObjectName("label_error_ciudad")
        self.gridLayout.addWidget(self.label_error_ciudad, 3, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_rut = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_rut.setObjectName("lineEdit_rut")
        self.gridLayout.addWidget(self.lineEdit_rut, 1, 1, 1, 1)
        self.lineEdit_direccion = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_direccion.sizePolicy().hasHeightForWidth())
        self.lineEdit_direccion.setSizePolicy(sizePolicy)
        self.lineEdit_direccion.setObjectName("lineEdit_direccion")
        self.gridLayout.addWidget(self.lineEdit_direccion, 2, 1, 1, 1)
        self.lineEdit_nombre = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.gridLayout.addWidget(self.lineEdit_nombre, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_error_nombre = QtGui.QLabel(self.groupBox)
        self.label_error_nombre.setMinimumSize(QtCore.QSize(260, 0))
        self.label_error_nombre.setObjectName("label_error_nombre")
        self.gridLayout.addWidget(self.label_error_nombre, 0, 2, 1, 1)
        self.label_error_direccion = QtGui.QLabel(self.groupBox)
        self.label_error_direccion.setObjectName("label_error_direccion")
        self.gridLayout.addWidget(self.label_error_direccion, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_error_rut = QtGui.QLabel(self.groupBox)
        self.label_error_rut.setMinimumSize(QtCore.QSize(177, 20))
        self.label_error_rut.setText("")
        self.label_error_rut.setObjectName("label_error_rut")
        self.gridLayout.addWidget(self.label_error_rut, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_ciudad = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ciudad.setObjectName("lineEdit_ciudad")
        self.gridLayout.addWidget(self.lineEdit_ciudad, 3, 1, 1, 1)
        self.lineEdit_giro = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_giro.setObjectName("lineEdit_giro")
        self.gridLayout.addWidget(self.lineEdit_giro, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.spinBox_num_mesas = QtGui.QSpinBox(self.groupBox)
        self.spinBox_num_mesas.setObjectName("spinBox_num_mesas")
        self.gridLayout.addWidget(self.spinBox_num_mesas, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.pushButton_guardar = QtGui.QPushButton(self.groupBox)
        self.pushButton_guardar.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_guardar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.gridLayout_2.addWidget(self.pushButton_guardar, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(FormularioEmpresa)
        QtCore.QMetaObject.connectSlotsByName(FormularioEmpresa)

    def retranslateUi(self, FormularioEmpresa):
        FormularioEmpresa.setWindowTitle(QtGui.QApplication.translate("FormularioEmpresa", "Datos de la Empresa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error_email.setText(QtGui.QApplication.translate("FormularioEmpresa", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error_giro.setText(QtGui.QApplication.translate("FormularioEmpresa", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Debe tener sólo letras</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error_ciudad.setText(QtGui.QApplication.translate("FormularioEmpresa", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Debe tener sólo letras</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FormularioEmpresa", "Rut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FormularioEmpresa", "Direccion", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FormularioEmpresa", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error_nombre.setText(QtGui.QApplication.translate("FormularioEmpresa", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Debe tener sólo letras</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error_direccion.setText(QtGui.QApplication.translate("FormularioEmpresa", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Debe tener sólo letras</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FormularioEmpresa", "Fono", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FormularioEmpresa", "Ciudad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FormularioEmpresa", "Giro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FormularioEmpresa", "E-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FormularioEmpresa", "Numero de mesas", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_guardar.setText(QtGui.QApplication.translate("FormularioEmpresa", "GUARDAR", None, QtGui.QApplication.UnicodeUTF8))

